### ISSUE TITLE
help

### ISSUE THREAD

**Issue by freezing2688** [Y3t1y3t/CSGO-Extern#1]
is the project can send command to csgo ? just like use toggleconsole ? please

**Comment by Y3t1y3t** [comment]
Hi,
yes, that is one of it's features:
`
    CSGO::gEngineClient->ClientCmdUnrestricted( "say wasup" );
`

**Comment by freezing2688** [comment]
oh yes! that's very useful, nice job! :)

**Comment by Y3t1y3t** [comment]
thank you. i'll close this issue now. if you have any other question regarding this project feel free to ask.
